use serde::{Serialize, Deserialize};
/**A five-tier risk assessment for the transaction, based on the probability distribution of ACH returns, measured by the incident rate.

Each tier corresponds to a distribution with a different mean (average) probability.

`HIGH`: The mean probability of ACH return risk is above 40%.
`MEDIUM_HIGH`: The mean probability of ACH return risk is 15%-40%.
`MEDIUM`: The mean probability of ACH return risk is 5-10%.
`MEDIUM_LOW`: The mean probability of ACH return risk is 1%-2%.
`LOW`: The mean probability of ACH return risk is below 1%.

Note that these tiers correspond to probability *distributions* and not to discrete probabilities.

These tier definitions are specific to Balance Plus and do not apply to risk tiers generated by other Plaid endpoints.*/
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum BalancePlusRiskLevel {
    #[serde(rename = "HIGH")]
    High,
    #[serde(rename = "MEDIUM_HIGH")]
    MediumHigh,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "MEDIUM_LOW")]
    MediumLow,
    #[serde(rename = "LOW")]
    Low,
}
